import datetime
x=datetime.datetime.now()
print("Current Date and Time:",x)
print(x.today())
print("Manually print date and time")
print("x.day,""/",x.month,"/",x.year)
print(x.date())
print(x.hour,":",x.minute,":",x.second)
print(x.time())
print("No. of week days:",x.weekday())
#Create date
year=int(input("Enter year:"))
month=int(input("Enter month:"))
day=int(input("Enter day:"))
h=int(input("Enter hours:"))
m=int(input("Enter minutes:"))
s=int(input("Enter seconds:"))
x1=datetime.datetime(year,month,day,h,m,s)
print(x1)