rollno=int(input("Enter Rollno:"))
Maths=int(input("Enter maths marks:"))
Sci=int(input("Enter Sci marks:"))
Eng=int(input("Enter eng marks:"))
total=(Maths+Sci+Eng)
per=(total/3)
print("rollno",rollno)
print("total",total)
print("per",per)
