name=input("Enter your name")
percentage=input("Enter your percentage:")
mobno=input("Enter your mob no:")
sentence="The name of the students is{},his percntage is{} and mobile number is{}".format(name,percentage,mobno)
print(sentence)