import math
a=math.sin(0.5)
print(a)
a=math.cos(0.5)
b=math.tan(0.5)
c=math.log(1)
d=math.pow(2,4)
e=math.sqrt(100)
f=math.sqrt(3)
g=math.ceil(4.587)
h=math.floor(4.587)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print("abs fun:",abs(-9))
print("Min fun:",min(-9,89,58))
print("Max fun:",max(-9,89,58))
print("Factorial Fun:",math.factorial(5))
print("Hypot Fun:",math.hypot(3,4))


