s=("Heyram said:Quality is show our silent personality")
print(s)
print("length of s=",len(s))
print("The first occourence of the letter a=",s.index('a'))
print("t occours",s.count('t'),"times.")
print("The first five characters are:",s[:5])
print("The next five char are:",s[5:10])
print("The 13th char is:",s[12])
print("The char with odd index are:",s[1::2])
print("The char with even index are:",s[0::2])
print("The last five char are:",s[-5:])
print("The next five last char are:",s[-10:-5])
print("Uppercase of string is",s.upper())
print("The lower case are",s.lower())
